### PR TITLE
swift3 support

### PR DESCRIPTION
**Pull request by coutar-t**
Swift3 support

### CODE REVIEW

**Comment by kostiakoval** [comment]
Looks line tests are failing on travis :(

**Comment by coutar-t** [comment]
Yes, i'll correct it asap

**Comment by kostiakoval** [comment]
hi @coutar-t  is there any change  you could look at fixing travis integration?

**Comment by coutar-t** [comment]
As i think Travis try to compile it in swift 2 and not swift 3. When I compile it on my computer with swift 3 it works. In the configuration, travis uses a xcode 7.1 image.

**Comment by kostiakoval** [comment]
thanks I will have a look on it

**Comment by dmorrow** [comment]
@kostiakoval see #12

**Comment by kostiakoval** [comment]
let's see if this will work now

**Comment by kostiakoval** [comment]
the swift 3 changes looks good so I decided to merge it anyway. Now lets fix the travis

**Comment by kostiakoval** [comment]
travis is fixed . https://travis-ci.org/kostiakoval/SpeedLog

**Pull request merged**
