### PR TITLE
Update to swift2 syntax

### PR DESCRIPTION
**Pull request by phimage**

### CODE REVIEW

**Comment by kostiakoval** [comment]
:100: :100: :100: Thx. Did't have time to do that

Giphy

**Comment by kostiakoval** [comment]
@phimage are you on Twitter? want to connect with you!

**Comment by phimage** [comment]
no twitter yet

If you have time, increment podspec version
and `pod trunk push`

**Comment by kostiakoval** [comment]
Ok, I will

**Comment by kostiakoval** [comment]
@phimage  Done !!! Thxt for help

**Pull request merged**
