### PR TITLE
Use xcode8 osx_image for Swift 3 tests

### PR DESCRIPTION
**Pull request by dmorrow**

### CODE REVIEW

**Comment by kostiakoval** [comment]
the test are failing, that weird but lets merge it anyway

**Comment by kostiakoval** [comment]
@dmorrow  Do you have any idea why it's failing?

**Comment by dmorrow** [comment]
@kostiakoval I haven't looked at the XCode Project, but the error says 

> xcodebuild: error: Failed to build project SpeedLog with scheme SpeedLog.
>     Reason: A build only device cannot be used to run this target.

**Comment by kostiakoval** [comment]
@dmorrow Really thanks for your PR. this fix was merged in #11

**Comment by kostiakoval** [comment]
thanks for the help, travis is fixed. I had to specify -destination 
travis is fixed . https://travis-ci.org/kostiakoval/SpeedLog

**Pull request closed without merging**
